modid = "hexecuteif"
book = "hexcasting:thehexbook"

resource_dirs = [  # top takes priority
    "resources",
    "{$_common.src}/main/resources",
    { path="{$_common.src}/generated/resources", required=false },
    "{$_fabric.src}/main/resources",
    { path="{$_fabric.src}/generated/resources", required=false },
    "{$_forge.src}/main/resources",
    { path="{$_forge.src}/generated/resources", required=false },
    { modid="hexcasting" },
    { modid="minecraft" },
    { modid="hexdoc" },
]
export_dir = "src/hexdoc_hexecuteif/_export/generated"

[template]
icon = "{$_common.src}/main/resources/assets/hexecuteif/icon.png"
include = [
    "hexecuteif",
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "HexecuteIf"
author = "n08i40k"
show_landing_text = false

[extra.hexcasting]
# NOTE: "!Raw" means "don't apply variable interpolation to this value"
_pattern_regex = { "!Raw"='make\("(?P<name>[^"]+)",\s*HexDir\.(?P<startdir>\w+),\s*"(?P<signature>[qweasd]+)"' }

[[extra.hexcasting.pattern_stubs]]
path = "{$_common.kotlin}/registry/HexecuteIfActions.kt"
regex = "{^_pattern_regex}"

# platforms

[_common]
src = "../common/src"
java = "{src}/main/java/ru/n08i40k/hexecuteif"
kotlin = "{src}/main/kotlin/ru/n08i40k/hexecuteif"

[_fabric]
src = "../fabric/src"
java = "{src}/main/java/ru/n08i40k/hexecuteif/fabric"
kotlin = "{src}/main/kotlin/ru/n08i40k/hexecuteif/fabric"

[_forge]
src = "../forge/src"
java = "{src}/main/java/ru/n08i40k/hexecuteif/forge"
kotlin = "{src}/main/kotlin/ru/n08i40k/hexecuteif/forge"
